server:
  port: 8193
  servlet:
    context-path: /auth-service
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/imarket
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
jwt:
  secret: oifh4309frthuihihihergjneojgnoejgoij394ut93n(*Unoj0))()kjfjo
  lifetime: 36000000

