version: '3'

services:

  mysql:
    image: mysql:8.0.25
    domainname: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=imarket
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./tmp/db_dump:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "root" ,"ping", "-h", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10

  #flyway:
  #  image: boxfuse/flyway
  #  command: -url=jdbc:mysql://mysql:3306?allowPublicKeyRetrieval=true&useSSL=false -schemas=imarket -user=root -password=admin -connectRetries=10 migrate
  #  volumes:
  #    - ./flyway:/flyway/sql
  #  depends_on:
  #    - mysql

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"