server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8191/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-service
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8193/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter


jwt:
  secret: oifh4309frthuihihihergjneojgnoejgoij394ut93n(*Unoj0))()kjfjo
  lifetime: 36000000

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
