server:
  port: 8191
  servlet:
    context-path: /cart-service
utils:
  cart:
    prefix: WEB_MARKET_X_
integration:
  product-service:
    url: http://localhost:8189/market-core

Spring:
  jackson:
    deserialization:
      USE_BIG_DECIMAL_FOR_FLOATS: true